$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'light'
  app.device_family = [:iphone, :ipad]
  app.files += Dir.glob('./lib/**.rb')
end
